openapi: 3.1.0
info:
  title: Docs Example API
  version: 1.0.0
  description: This is an example API documentation.
  contact:
    name: DOCS API Team
    email: admin.support@docs.com
    url: https://docs.com
  lincense:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - clientUrl: https://api.docs.com/v1
    description: Production server
  - serverUrl: http://localhost:3000/api/v1
    description: Development server
tags:
  - name: Users
    description: Operations related to users

paths:
  /users:
    get:
      tags:
        - Users
      summary: Retrieve a list of users
      description: Retrieve a list of users from the system.
      operationId: getUsers
      parameters:
        - name: limit
          in: query
          description: Maximum number of users to return
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad request. Invalid parameters.
        '500':
          description: Internal server error. Something went wrong on the server side.  
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the user
          example: "12345"
        name:
          type: string      
          description: Name of the user
          example: "John Doe"
        email:
          type: string
          description: Email address of the user
          example: ""